### ISSUE TITLE
Always returns 1

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/fastd-verify#3]
```
verify command exited with status 1
AttributeError: __exit__
    with config['default'] as c:
  File "/usr/local/bin/fastd-verify", line 182, in main
    returnCode = main()
  File "/usr/local/bin/fastd-verify", line 199, in <module>
Traceback (most recent call last):

```

**Comment by RubenKelevra** [comment]
fixed

https://github.com/VfN-NRW/fastd-verify/commit/eee5bc2d84bce411e276f879f6f8bcdfd4b988a7
